export const seoPages = {
  "/drip-irrigation-kenya": ["Drip Irrigation Systems in Kenya", "Plan and buy reliable drip irrigation systems for Kenyan farms, with product selection, sizing advice, installation and nationwide delivery.", "A good drip system matches crop spacing, field size, water quality and available pressure. DripTech helps you select the complete system rather than isolated parts.", ["Driplines and emitters", "Filtration and pressure regulation", "Mainlines, valves and fittings"]],
  "/drip-irrigation-kit-price-kenya": ["Drip Irrigation Kit Prices in Kenya", "Compare drip irrigation kit requirements and request current Kenya pricing based on acreage, crop spacing and water source.", "Kit pricing varies with field dimensions, row spacing, filtration, pipe lengths, pump requirements and installation. Share your farm details for an accurate parts list.", ["Acreage-based sizing", "Transparent product pricing", "Optional installation support"]],
  "/driplines-for-sale-kenya": ["Driplines for Sale in Kenya", "Shop driplines and matching connectors in Kenya with guidance on spacing, wall thickness, flow and filtration.", "Select dripline by crop pattern, run length, pressure and water quality—not price alone. Correct filtration and flushing are essential for reliable operation.", ["Different emitter spacings", "Matching start connectors", "Filtration and flushing advice"]],
  "/sprinkler-systems-kenya": ["Sprinkler Systems in Kenya", "Buy and install farm sprinkler systems in Kenya, including sprinklers, rain guns, pumps, pipes, valves and controls.", "Sprinkler selection depends on required radius, flow, wind, pump duty and field layout. We help match each component to a workable operating zone.", ["Field sprinklers", "Rain guns and stands", "Pump and pipe sizing"]],
  "/irrigation-companies-kenya": ["Irrigation Company in Kenya", "DripTech Eco Flow supplies, designs, installs and supports irrigation systems for farms across Kenya.", "Choose an irrigation partner that can explain the design, supply compatible equipment and support the system after installation.", ["Design and quotations", "Equipment supply", "Installation and maintenance"]],
  "/solar-irrigation-pumps-kenya": ["Solar Irrigation Pumps in Kenya", "Plan solar-powered irrigation pumping in Kenya with practical guidance on water source, head, flow and system demand.", "A pump should be selected from measured head and required flow. Solar array and controller sizing must follow the pump duty and daily irrigation target.", ["Borehole and surface options", "Head and flow assessment", "Irrigation demand matching"]],
  "/borehole-water-pumps-kenya": ["Borehole Water Pumps in Kenya", "Find borehole pumps for irrigation and water supply in Kenya with help sizing head, flow, power and pipework.", "Borehole depth alone does not size a pump. Static level, drawdown, delivery elevation, pipe losses and target flow all matter.", ["Submersible pump selection", "Pipe and cable planning", "Protection and controls"]],
  "/water-storage-tanks-kenya": ["Water Storage for Irrigation in Kenya", "Plan irrigation water storage, tank connections, valves, filters and distribution equipment in Kenya.", "Storage helps buffer variable water supply and irrigation demand. Tank volume and outlet arrangement should support the planned zones and refill cycle.", ["Storage sizing", "Tank outlet fittings", "Gravity or pumped distribution"]],
  "/greenhouse-drip-irrigation-kenya": ["Greenhouse Drip Irrigation in Kenya", "Design greenhouse drip irrigation and fertigation systems in Kenya for precise crop watering and feeding.", "Protected crops need uniform flow, dependable filtration and controllable fertigation. Layouts should reflect beds, plant spacing and daily crop demand.", ["Uniform drip application", "Fertigation equipment", "Zoning and control"]],
  "/fertigation-systems-kenya": ["Fertigation Systems in Kenya", "Buy and install fertigation equipment in Kenya for accurate nutrient injection through drip irrigation systems.", "Fertigation performance depends on injection method, filtration, pressure, water quality and correct flushing after feeding.", ["Venturi injectors", "Dosing and mixing", "Filters and non-return protection"]],
} as const;
