import { Link, createFileRoute } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { ArrowRight, Check, MessageCircle, ShoppingBag, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/storefront/product-card";
import { getFeaturedCatalogue } from "@/lib/catalog";
import { organizationSchema, pageHead, whatsappLink } from "@/lib/site";
import heroImage from "@/assets/driptech-field-hero.jpg";

const catalogueQuery = queryOptions({ queryKey: ["featured-catalogue"], queryFn: getFeaturedCatalogue, staleTime: 1000 * 60 * 10 });
export const Route = createFileRoute("/")({
  loader: ({ context }) => context.queryClient.ensureQueryData(catalogueQuery),
  head: () => ({ ...pageHead("/", "Drip Irrigation Kits, Pumps & Fittings Kenya | DripTech", "Shop drip irrigation kits, driplines, sprinklers, pumps, filters and fittings in Kenya. Get sizing advice and nationwide delivery from DripTech Eco Flow."), scripts: [{ type: "application/ld+json", children: JSON.stringify(organizationSchema) }] }),
  component: HomePage,
});
function HomePage() {
  const { data: products } = useSuspenseQuery(catalogueQuery);
  return <>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-12 sm:px-6 lg:grid-cols-12 lg:gap-12 lg:px-8 lg:py-16">
      <div className="rise-in lg:col-span-7"><p className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-muted px-3 py-1 text-xs font-semibold uppercase text-teal"><span className="size-1.5 rounded-full bg-accent" />Equipment for Kenyan farms</p><h1 className="max-w-[19ch] text-balance font-serif text-4xl font-bold leading-[1.08] sm:text-5xl lg:text-6xl">Irrigation that fits your farm—not the other way round.</h1><p className="mt-5 max-w-[48ch] text-base leading-7 text-muted-foreground sm:text-lg">Driplines, sprinklers, pumps, filters, controls and complete systems with clear specifications, practical sizing support and delivery across Kenya.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/products">Browse all products <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="outline"><a href={whatsappLink("Hello DripTech, please help me size an irrigation system for my farm.")} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />WhatsApp sizing help</a></Button></div><div className="mt-8 grid gap-3 text-sm text-muted-foreground sm:grid-cols-3">{["Complete live catalogue", "Technical sizing support", "Delivery across Kenya"].map((item) => <span key={item} className="flex items-center gap-2"><Check className="size-4 text-teal" />{item}</span>)}</div></div>
      <div className="rise-in-late lg:col-span-5"><div className="relative pb-5 pl-3 sm:pl-6"><img src={heroImage} alt="Drip-irrigated vegetable farm with visible drip lines" width={1024} height={1280} fetchPriority="high" className="aspect-[4/5] w-full rounded-lg object-cover" /><div className="absolute bottom-0 left-0 max-w-[230px] rounded-md border border-border bg-background/95 px-4 py-3 shadow-lg"><p className="text-[10px] font-semibold uppercase text-teal">Need a complete system?</p><p className="mt-1 font-serif text-base font-bold">Tell us your acreage and crop.</p><p className="mt-1 text-xs text-muted-foreground">We’ll prepare the right parts list.</p></div></div></div>
    </section>
    <section className="border-y border-border bg-muted/40"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-6 text-sm sm:grid-cols-3 sm:px-6 lg:px-8"><span><strong>1,200+</strong> live product records</span><span><strong>14</strong> specialist categories</span><span><strong>Nationwide</strong> delivery support</span></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase text-teal">Popular equipment</p><h2 className="font-serif text-3xl font-bold">Choose with confidence</h2><p className="mt-2 max-w-[54ch] text-sm text-muted-foreground">Real products, listed prices, specifications and stock status from our live catalogue.</p></div><Link to="/products" className="inline-flex items-center gap-2 text-sm font-semibold text-teal">View all products <ArrowRight className="size-4" /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 8).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-4 pb-14 sm:px-6 lg:grid-cols-12 lg:px-8"><div className="rounded-lg bg-brand-dark p-7 text-brand-light lg:col-span-5 lg:p-8"><p className="text-xs font-semibold uppercase text-gold">Buying guide</p><h2 className="mt-3 font-serif text-2xl font-bold">Not sure what fits your farm?</h2><p className="mt-3 text-sm leading-6 text-brand-light/70">Send your acreage, crop and water source. Our team will help size the driplines, pump, filter and fittings before you order.</p><Button asChild className="mt-6 bg-gold text-brand-dark hover:bg-gold/90"><a href={whatsappLink("Hello DripTech. My farm size is: ___. My crop is: ___. My water source is: ___. Please help me size the system.")} target="_blank" rel="noreferrer">Start a sizing request <ArrowRight className="size-4" /></a></Button></div><div className="grid gap-5 sm:grid-cols-2 lg:col-span-7"><div className="rounded-lg border border-border bg-card p-6"><Truck className="size-5 text-teal" /><h3 className="mt-5 font-serif text-lg font-bold">Plan your delivery</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Confirm stock, destination and dispatch timing with our team before payment.</p></div><div className="rounded-lg border border-border bg-card p-6"><ShoppingBag className="size-5 text-teal" /><h3 className="mt-5 font-serif text-lg font-bold">From parts list to field</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Get help with system design, installation planning and every fitting needed.</p></div></div></section>
  </>;
}
