import { ArrowRight, Check, Mail, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { contentPages } from "@/lib/content-pages";
import { SITE, whatsappLink } from "@/lib/site";
export function ContentPage({ path }: { path: string }) {
  const page = contentPages[path];
  if (!page) return null;
  return <><section className="border-b border-border bg-muted/40"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase text-teal">{page.eyebrow}</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-bold leading-tight sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">{page.intro}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><a href={whatsappLink(`Hello DripTech, I need help with ${page.title.toLowerCase()}.`)} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />{page.cta ?? "Talk to our team"}</a></Button>{path === "/contact" && <><Button asChild size="lg" variant="outline"><a href={`tel:${SITE.phone}`}><Phone className="size-4" />Call us</a></Button><Button asChild size="lg" variant="outline"><a href={`mailto:${SITE.email}`}><Mail className="size-4" />Email</a></Button></>}</div></div></section><section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-3">{page.points.map((point, index) => <article key={point.title} className="bg-card p-7"><span className="grid size-8 place-items-center rounded-full bg-secondary text-sm font-bold text-secondary-foreground">{index + 1}</span><h2 className="mt-5 font-serif text-xl font-bold">{point.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{point.text}</p></article>)}</div><div className="mt-10 border-y border-border py-8"><h2 className="font-serif text-2xl font-bold">What to share with us</h2><div className="mt-4 grid gap-3 text-sm text-muted-foreground sm:grid-cols-2 lg:grid-cols-4">{["Your location and acreage", "Crop and row spacing", "Water source and flow", "Photos or existing layout"].map((item) => <span key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-teal" />{item}</span>)}</div><a href={whatsappLink(`Hello DripTech, I would like to discuss ${page.title.toLowerCase()}.`)} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-teal">Discuss your requirements <ArrowRight className="size-4" /></a></div></section></>;
}
